name: dart_actor
description: experimental akka actor implementation for using in dart.
version: 0.0.1
#homepage: https://github.com/Aaaaash/dart-actor
#author: Aaaaash <binshao54@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  event_bus: 0.4.1

dev_dependencies:
  test: ^0.12.0
