name: dart_actor
description: experimental akka actor implementation for using in dart.
version: 0.0.1
homepage: https://github.com/FE-Ractor/dart-actor
authors: [Aaaaash <binshao54@gmail.com>, Corol <akira.binjie@gmail.com>]

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  event_bus: ^1.0.1
  uuid: ^1.0.1

dev_dependencies:
  test: ^1.5.1+1
