name: dart_actor
description: experimental akka actor implementation for using in dart.
version: 0.1.4
homepage: https://github.com/FE-Ractor/dart-actor

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  event_bus: ^1.0.1
  uuid: ^2.0.0

dev_dependencies:
  test: ^1.5.1+1
